name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: node:12.22.0-alpine3.10
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release